apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  source:
    path: ch03/cert-manager
    repoURL: https://github.com/safe2008/ArgoCD-in-Practice.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true