apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/safe2008/ArgoCD-in-Practice.git
    targetRevision: main
    path: ch03/falco

  destination:
    namespace: falco
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
