apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-rollouts-ui
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/proxy-body-size: 100M
    ingress.kubernetes.io/app-root: "/"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - http:
        paths:
          - path: /dashboard
            pathType: Prefix
            backend:
              service:
                name: argo-rollouts-dashboard
                port:
                  number: 3100
  # - host: argo-rollouts.10.200.181.87.nip.io
  #   http:
  #     paths:
  #     - backend:
  #         service:
  #           name: argo-rollouts-dashboard
  #           port:
  #             number: 3100
  #       path: "/"
  #       pathType: ImplementationSpecific
  # tls:
  # - hosts:
  #   - argocd.10.200.181.87.nip.io
  #   secretName:  wildcard-tools-credential