apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml
- https://raw.githubusercontent.com/argoproj/argo-rollouts/master/manifests/dashboard-install.yaml
- resources/argo-rollouts-ingress.yaml

# Adds the argo-rollouts namespace to all resources, which is required anyhow.
namespace: argo-rollouts