apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata:
  name: argocd-prod
spec: 
  destination: 
    namespace: argocd-prod
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: ch7/initial-setup/argocd-prod
    repoURL: https://github.com/safe2008/ArgoCD-in-Practice.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
