sonarqube:
  ingress:
    enabled: true
    hosts:
      - name: sonarqube.192.168.1.54.nip.io
        path: "/"
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      ingress.kubernetes.io/proxy-body-size: 100M
      ingress.kubernetes.io/app-root: "/"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    tls:
    - hosts:
      - sonarqube.192.168.1.54.nip.io
      secretName:  sonarqube-credential