sonarqube:
  ingress:
    enabled: true
    hosts:
      - name: sonarqube.192.168.1.54.nip.io
        path: "/*"
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      ingress.kubernetes.io/proxy-body-size: 100M
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.allow-http: "false"