sonarqube:
  image:
    repository: sonarqube
    tag: 9.2.4-enterprise
  ingress:
    enabled: true
    hosts:
      - name: sonarqube.192.168.1.54.nip.io
        path: "/"
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      kubernetes.io/ingress.allow-http: "false"
    ingressClassName: nginx
    tls:
    - secretName: sonarqube-tls
      hosts:
        - sonarqube.192.168.1.54.nip.io