apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluegreen-demo-preview
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/blue-green-preview"
        backend:
          service:
            name: bluegreen-demo-preview
            port:
              number: 8080
