kind: Pod
apiVersion: v1
metadata:
  name: hello-app
  labels:
    app: hello
spec:
  containers:
  - name: hello-app
    image: nginxdemos/hello:plain-text
    imagePullPolicy: Always
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
spec:
  rules:
    - host: hello.boriphuth.trueddns.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: hello-service
                port:
                  number: 80