apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: boriphuth.sa@gmail.com
    privateKeySecretRef:
      name: vault-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx