apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceBlacklist:
  - group: velero.io
    kind: Backup
  - group: velero.io
    kind: PodVolumeBackup
  orphanedResources:
    ignore:
    - kind: Secret
      name: sh.helm.release.v1.argocd.*
    - kind: ConfigMap
      name: istio-ca-root-cert
    - kind: Secret
      name: '*-tls'
    warn: true
  sourceRepos:
  - '*'
